global:
  checkNewVersion: false
  sendAnonymousUsage: false

api:
  dashboard: true
  insecure: false
  debug: false
  disableDashboardAd: true

log:
  level: INFO
  format: common

accessLog:
  format: common
  bufferingSize: 100
  fields:
    headers:
      defaultMode: drop

entryPoints:
  web:
    address: ":80"
    transport:
      lifeCycle:
        graceTimeOut: 20s
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"
    transport:
      lifeCycle:
        graceTimeOut: 20s
    http:
      tls:
        certResolver: letsencrypt
  ping:
    address: ":8082"

ping:
  entryPoint: ping

providers:
  docker:
    endpoint: "tcp://socket-proxy:2375"
    exposedByDefault: false
    network: traefik-net
  file:
    directory: /etc/traefik/dynamic
    watch: true

certificatesResolvers:
  letsencrypt:
    acme:
      storage: /etc/traefik/acme/acme.json
      dnsChallenge:
        provider: tencentcloud
        resolvers:
          - "119.29.29.29:53"
          - "182.254.116.116:53"
