replication_factor = 1
consistency_mode = "consistent"

metadata_dir = "/var/lib/garage/meta"
data_dir = "/var/lib/garage/data"
metadata_snapshots_dir = "/var/lib/garage/meta/snapshots"
metadata_fsync = true
data_fsync = true
metadata_auto_snapshot_interval = "24h"

db_engine = "sqlite"
block_size = "1M"
block_ram_buffer_max = "64MiB"
block_max_concurrent_reads = 8
block_max_concurrent_writes_per_request = 3
compression_level = 1

rpc_bind_addr = "127.0.0.1:3901"
rpc_public_addr = "127.0.0.1:3901"
allow_world_readable_secrets = false

[s3_api]
api_bind_addr = "[::]:3900"
s3_region = "garage"

[s3_web]
bind_addr = "[::]:3902"
root_domain = ".web.garage"
index = "index.html"
